Flowpack:
  Expose:
    Pagination:
      DefaultLimit: 10
      MaxPages: 10
      Limits:
        - 10
        - 20
        - 30
        - 50
        - 100

    Controls:
      string: 'Textfield'
      integer: 'Textfield'
      float: 'Textfield'
      boolean: 'Checkbox'
      array: 'Select'
      '\DateTime': 'DateTime'

    Menu: []

    ClassSchemaSources:
      - '\Flowpack\Expose\Reflection\Sources\DefaultSource'
      - '\Flowpack\Expose\Reflection\Sources\PhpSource'
      # - '\Flowpack\Expose\Reflection\Sources\AnnotationSource'
      - '\Flowpack\Expose\Reflection\Sources\YamlSource'