Flowpack:
  Expose:
    Pagination:
      DefaultLimit: 10
      MaxPages: 10
      Limits:
        - 10
        - 20
        - 30
        - 50
        - 100

    FieldTypes:
      string: 'Textfield'
      integer: 'Textfield'
      float: 'Textfield'
      boolean: 'Checkbox'
      array: 'Select'
      '\DateTime': 'Textfield'

    Menu: []